blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/Aprasaks/nexus-blog/discussions
    about: ì§ˆë¬¸ì´ë‚˜ ì•„ì´ë””ì–´ ê³µìœ ëŠ” ì—¬ê¸°ì„œ!
  - name: ğŸ“š Documentation
    url: https://github.com/Aprasaks/nexus-blog/wiki
    about: í”„ë¡œì íŠ¸ ë¬¸ì„œ ë° ê°€ì´ë“œ